authorize:
  required: "Для данной операции необходима авторизация"
  wrong: "Неверное имя пользователя или пароль"
  already_exists: "Пользователь с таким именем уже существует"
  wrong_captcha: "Неверный код"
  admin_required: "Для данной операции требуются права администратора"
  banned: "Пользователь заблокирован администратором"
  wrong_key_or_password: "Неверный ключ или пароль для выполнения данной операции"
  wrong_key_or_password_format: "Неверный формат ключа или пароля. Убедитесь что вы вводите полный ключ или пароль!"
parameters:
  wrong_set: "Недопустимая комбинация параметров"
  should_be: "Параметр '%s' должен присутствовать и иметь тип '%s'"
  password_should_be_gt: "Размер пароля должен быть больше чем %d символов"
  login_wrong_symbols: "Логин содержит недопустимые символы. Допустимы только 'a-z', 'A-Z', цифры и '-'"
  should_be_image: "В поле картинки должен присутствовать URL картинки (с соответствующим расширением)."
  wrong_utf8: "Обнаружены неверные данные UTF8 в теле или заголовке сообщения."
users:
  absent_id: "Пользователь с таким ID не существует"
  more_vote_power: "Недостаточно силы голоса для такого голосования. Пожалуйста, накопите силу голоса перед повторением данного действия."
  already_voting: "Такой голос уже зарегистрирован."
info:
  under_contruction: "Еще не реализовано - находится в разработке."
  data_absent: "Данные не найдены"
  different_users: "Для выполнения операции необходимо быть автором данного контента"
content:
  already: "Такая статья или комментарий уже существуют! Поменяйте заголовок или воспользуйтесь редактированием."
  alian: "Вы не можете изменять чужой контент"
  frozen: "Истек срок в течении которого можно было производить данное действие"
  comment_need_wait: "Вы пытаетесь постить слишком часто. Подождите некоторое время и попробуйте снова."
  vote_time_exired: "Время для голосования за этот контент закончилось."
  absent: "Невозможно найти данный контент для совершения с ним операций. Извините."
announce:
  already_exists: "Анонс данного произведения еще показывается на указаной странице. Вы можете анонсировать его повторно только когда оно исчезнет из показа."
  not_enough_money: "У вас недостаточно средств для выполнения операции"
invite:
  already_exists: "Приглашение еще показывается в блоке приглашений. Вы можете создать его повторно только когда оно исчезнет из показа."
transfer:
  not_enough_money: "У вас недостаточно средств для выполнения операции"
